#!/bin/bash
python /data/harvestWAF.py /data/WAFHarvests/Geologic_Discipline_\(legacy_programs\)/harvested/ http://geo-nsdi.er.usgs.gov/waf/ .xml /data/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Water_National_Spatial_Data_Infrastructure_Node/ http://water.usgs.gov/GIS/metadata/usgswrd/XML/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Mineral_Resources_WAF_MERGE_WITH_Mineral_Resources_Program/ http://mrdata.usgs.gov/metadata/waf/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Earth_Resources_Observation_and_Science https://dds.cr.usgs.gov/ee-data/sdc/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Airborne_WAF_MERGE_WITH_Mineral_Resources_Program/ http://mrdata.usgs.gov/geophysics/surveys/waf/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Coastal_and_Marine_Geology_Program/ http://cmgds.marine.usgs.gov/metadata/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/USGS_National_Geologic_Map_Database https://ngmdb.usgs.gov/geoDataGov/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 false
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Alaska_Science_Center http://alaska.usgs.gov/data/metadata/indexMA.php .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Energy_Resources_Program_WAF http://certmapper.cr.usgs.gov/data_gov/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
#/usr/bin/python3.4 harvestWAF.py /data/Mercury_instances/devcatalog/WAFHarvests/Columbia_Environmental_Research_Center https://www.cerc.usgs.gov/data/metadata/ .xml /data/Mercury_instances/devcatalog/harvesting_logs/WAF_harvester-`date +\%m\%d\%y`.log 2>&1 true
